### ISSUE TITLE
'Object of class Closure could not be converted to string' when mixing $factory and string in configuration

### ISSUE THREAD

**Issue by mindofmicah** [laracasts/TestDummy#59]
This is my first day working with TestDummy so let me know if there is a better way to accomplish what I'm trying.

I'm looking to use TestDummy to generate random data, but to have a little bit of control over the output. For a Venue entity, instead of using $factory->sentence to get nonsense, I'd like to make use of Faker's abilities and get names like:
>Bobby's Bar
>Susan's Grille

I can do this without a problem when using faker straight up
```php
echo "{$faker->firstName}'s {$faker->randomElement(['Bar', 'Grille'])};"
```
but when I try using TestDummy I get the error
```
'Object of class Closure could not be converted to string'
```
I'm trying
```php
$factory('Venue', [
    'name'=>$faker->firstName . "'s "
]);
```
but the concatenating makes the tool get angry.

**Comment by swekaj** [comment]
This is because the FakerAdapter class wraps all calls to the actual Faker class in a closure.  I think this is done because otherwise when the factory file is parsed all dummies would have the same value for their attributes.  While the factory is being built the closures are executed, generating a new value each time.

In order to get around this you can use your own closure.  Example:
```
$factory('Venue', [
    'name' => function () use ($faker) {
        $name = $faker->firstname;
        $type = $faker->randomElement([ 'Bar', 'Grille' ]);
        return $name() . "'s " . $type();
    }
]);
```
Or you can grab the Faker class directly with `$faker->generator()`, however if you do that each instance will have the same name since the name will be generated once when the factory file is included.

While this isn't ideal, there's not really a way around it.  Without wrapping the Faker calls in a closure when the factory file is included all of them would be run and every instance of the dummy would have the same generated values.  The only way I can see around it would be to use closures in factory file, but that would require a major overhaul.

**Comment by swekaj** [comment]
@JeffreyWay Are you interested in a pull request that does what I described above?  Enable passing a closure to `$factory()` instead of an array of attributes, and have the closure return the array of attributes.  This way it's a bit simpler to do complex attributes, especially attributes that might depend on other attributes.

**Comment by p4bloch** [comment]
Thanks @swekaj! I was *really* struggling with this :)

**Comment by laracasts** [comment]
@swekaj - Hmm, not sure. I wouldn't mind looking at a PR, though! What's wrong with just passing a closure for any array attributes that you need to use multiple Faker params for (like you said)?

**Comment by mindofmicah** [comment]
sorry that I didn't respond after the first response. Just wanted to let you know, @swekaj that your advice worked flawlessly and really helped me out.

**Comment by swekaj** [comment]
@laracasts I opened the PR (#63).  The problem I see with my initial solution presented here is that it's more complex.  

* First, you'd need to create a closure for each attribute that has complex needs.  
* Second, you still have to make sure to execute the closures that the $faker variable returns, rather than just using them as if they were on the normal Faker generator.  
* Third, there are still some things you can't do, namely altering one or more attributes based on the resulting value of another attribute.  For instance, if there are two date fields (a 'start' and 'stop') and you want the 'stop' value to always be greater than the 'start' value, you can't really effectively do that now.

PR #63 solves all of those issues, and is backwards compatible.

**Comment by swekaj** [comment]
@mindofmicah @p4bloch Glad I could help.

**Comment by p4bloch** [comment]
My first attempt was to use $faker this way, but it did not work:
~~~php
$factory('Package', [
    'name' => 'Package ' . $faker->numberBetween(1, 20),
]);
~~~

This also did not work:
~~~php
$factory('Package', [
    'name' => function() use($faker){return 'Package ' . $faker->numberBetween(1, 20);}
]);
~~~

This *did* work:
~~~php
$factory('Package', [
    'name' => 'Package ' . $faker->generator()->numberBetween(1, 20)
]);
~~~

The problem also arised when trying to make a mathematical operation like multiplying:
~~~php
$factory('Package', [
    'price' => $faker->generator()->randomElement([100, 120, 150, 180, 200, 230]) * 100
]);
~~~

I think this is not *that* complex and can even be taken as a common pitfall because of the way Faker can be used outside of this package. Anyway, TestDummy proved to be amazingly useful so far. Thanks @laracasts! :dancers:

**Comment by swekaj** [comment]
The problem with that solution is that now every instance of Package created will have the same 'name' or 'price' because `$faker->generator()->*` is executed once when the factories file is included to load the factories.  If you want each instance of the Package dummy to have different values for those attributes you'd need to do something like

```
$factory('Package', [
    'name' => function () use ($faker) {
        return 'Package ' . $faker->generator()->numberBetween(1, 20);
    },
    'price' => function () use ($faker) {
        return $faker->generator()->randomElement([ 100, 120, 150, 180, 200, 230 ]) * 100;
    }
]);
```

Granted, that is simpler than what I was doing before (not making use of `$faker->generator()`), but it's still a bit more complicated (in my mind) than just 

```
$factory('Package', function ($faker) {
    return [
        'name' => 'Package ' . $faker->numberBetween(1, 20),
        'price' => $faker->randomElement([100, 120, 150, 180, 200, 230]) * 100
    ];
});
```

This is especially so if there were several fields that needed closures.

And even if we agree it's not too complicated, it still doesn't address the issue of fields that depend on what is entered for other fields (see my start and stop fields example above).

I second the thanks to @laracasts, this is a great package.  I just think it could be even greater.

**Comment by p4bloch** [comment]
Another good use case for needing another field's info is when you have a polymorphic relationship between models. Staying with my example, I run into the situation where a Package could be owned by two separate models, with an `owner_type` field and an `owner_id` field, which depends on the previous one. Right now I had to create a different factory for each owner, and hardcode it right in.
